
server:
  port: 8081

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: Bravo_502
  jpa:
    hibernate:
      ddl-auto: update     # crucial for auto table creation
    show-sql: true          # optional, to see SQL logs
    database-platform: org.hibernate.dialect.PostgreSQLDialect